### ISSUE TITLE
sonoff-lan-config missing

### ISSUE THREAD

**Issue by Zodiac-69** [andreatondo/node-red-contrib-sonoff-lan-mode#1]
I add node-red-contrib-sonoff-lan-mode to NodeRED, i can see sonoff-lan-listener and sonoff-lan-control, but i do not see the config node.
It is shaded but not disabled when i look at the Pallet.
Am i missing something obvious?

**Comment by andreatondo** [comment]
@Zodiac-69 Thanks for writing.
The config node can be configured in the sonoff-lan-listener and sonoff-lan-control.
You will need to edit them, and there select/add a new sonoff-lan-config node:

![image](https://user-images.githubusercontent.com/1841815/111544183-6081af80-8774-11eb-99f6-5aae0e364a8b.png)

![image](https://user-images.githubusercontent.com/1841815/111544367-a6d70e80-8774-11eb-969d-809330a53cfc.png)

Please let me know if this helps.

Also, I am going to improve the description, few days ago I noticed I haven't specified what kind of commands the sonoff-lan-control accepts. Currently you can send to it messages containing a payload of "on" or "off" strings, to turn on/off the sonoff.

**Comment by Zodiac-69** [comment]
Do i just put the RPI IP address in the Host field?

**Comment by andreatondo** [comment]
You need to put the Sonoff IP address in the Host field - port is fine with the default value

**Comment by Zodiac-69** [comment]
Thank you for the quick reply.
I shall then need to make my Sonoff units all "Static" IP's to not create issues.
I missed the point in the beginning as i thought it "Scan" your network and build a map of all the units.
Thank you again, i shall check when i get home later today
